#!/usr/bin/env python3
"""
Leukemia classifier built on top of the original DinoBloom-G pretrained model.

Input  (base): DinoBloom-G.pth  — original pretrained model (from Google Drive).
               ViT-Giant trained on 13M+ hematology images. We do NOT modify this file.
Output (ours): bloom_leukemia.pth — our model with the leukemia head baked in.

Architecture:
  DinoBloom-G backbone (ViT-G/14)
    - Early blocks : FROZEN    — preserves pretrained hematology knowledge
    - Last N blocks: TRAINABLE — adapted to our leukemia classes
  + Classification head (MLP): TRAINABLE — our addition on top

Data sources:
  - New Data/train.txt + val.txt  (pre-split, generated by make_splits.py)
  - New Data/extracted/archiveN/  (all archives auto-discovered, 80/20 split)
"""

import os
import sys
import argparse
import json
import csv
import time
import datetime
import subprocess
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path
import random
import warnings
import time as _time
from epoch_report import EpochReporter

# ── ANSI colour helpers (degrade gracefully if terminal doesn't support) ───────
_C = {
    "reset":  "\033[0m",
    "bold":   "\033[1m",
    "green":  "\033[92m",
    "yellow": "\033[93m",
    "red":    "\033[91m",
    "cyan":   "\033[96m",
    "blue":   "\033[94m",
    "grey":   "\033[90m",
    "white":  "\033[97m",
}
def _c(color, text): return f"{_C[color]}{text}{_C['reset']}"
def _acc_color(acc):
    if acc >= 90: return "green"
    if acc >= 75: return "yellow"
    return "red"
def _bar(val, total, width=30, fill="█", empty="░"):
    filled = int(width * val / max(total, 1))
    return fill * filled + empty * (width - filled)

REPO_ROOT     = Path(__file__).parent.resolve()
OCI_NAMESPACE = "idcsxwupyymi"
OCI_BUCKET    = "bloomi-training-data"

# Organize bucket by environment and SLURM job ID
_run_date  = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
_slurm_job = os.environ.get("SLURM_JOB_ID", "")
if _slurm_job:
    OCI_RUN_PREFIX = f"trained-models/unc-h200/job{_slurm_job}_{_run_date}"
else:
    OCI_RUN_PREFIX = f"trained-models/oracle-a100/{_run_date}"

def _oci_bin():
    """Find oci binary, checking common install locations."""
    import shutil, os
    oci = shutil.which("oci")
    if oci:
        return oci
    for p in [
        os.path.expanduser("~/.local/bin/oci"),
        os.path.expanduser("~/bin/oci"),
        "/usr/local/bin/oci",
    ]:
        if os.path.isfile(p):
            return p
    return "oci"  # last resort — let it fail with a clear error

def oracle_upload(local_path: str, object_name: str):
    """Upload a file to Oracle Object Storage with parallel multipart upload."""
    env = os.environ.copy()
    env["PATH"] = os.path.expanduser("~/.local/bin") + ":" + env.get("PATH", "")
    result = subprocess.run([
        _oci_bin(), "os", "object", "put",
        "--namespace", OCI_NAMESPACE,
        "--bucket-name", OCI_BUCKET,
        "--name", object_name,
        "--file", local_path,
        "--force",
        "--parallel-upload-count", "8",   # 8 parallel threads
        "--part-size", "128",              # 128MB parts
    ], env=env, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"oci put failed: {result.stderr.strip()}")
    print(f"  [oracle] uploaded → {OCI_BUCKET}/{object_name}")

def oracle_upload_bg(local_path: str, object_name: str):
    """Fire-and-forget background upload — training continues immediately."""
    import threading
    def _run():
        try:
            oracle_upload(local_path, object_name)
        except Exception as e:
            print(f"  [oracle-bg] WARNING: {object_name} upload failed — {e}", flush=True)
    t = threading.Thread(target=_run, daemon=True)
    t.start()
    print(f"  [oracle-bg] uploading in background → {object_name}", flush=True)
    return t

def oracle_delete(object_name: str):
    """Delete an object from Oracle Object Storage."""
    subprocess.run([
        "oci", "os", "object", "delete",
        "--namespace", OCI_NAMESPACE,
        "--bucket-name", OCI_BUCKET,
        "--object-name", object_name,
        "--force"
    ], check=True)
    print(f"  [oracle] deleted  → {OCI_BUCKET}/{object_name}")


def find_max_batch_size(model, device, amp_dtype, num_classes, start=32, max_batch=512):
    """Probe VRAM with a dummy forward+backward to find the largest safe batch size."""
    import gc
    ce = nn.CrossEntropyLoss()
    model.train()
    best = start
    batch = start
    print(f"\n  [batch-tuner] Probing VRAM  start={start}  cap={max_batch}", flush=True)
    while batch <= max_batch:
        try:
            torch.cuda.empty_cache(); gc.collect()
            x = torch.zeros(batch, 3, 224, 224, device=device)
            y = torch.zeros(batch, dtype=torch.long, device=device)
            with torch.amp.autocast("cuda", dtype=amp_dtype):
                out = model(x)
                loss = ce(out, y)
            loss.backward()
            model.zero_grad(set_to_none=True)
            del x, y, out, loss
            torch.cuda.empty_cache(); gc.collect()
            best = batch
            print(f"  [batch-tuner]   {batch:>4} ✓", flush=True)
            batch = batch * 2
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache(); gc.collect()
            print(f"  [batch-tuner]   {batch:>4} OOM → stop", flush=True)
            break
    # 80% of max, aligned to multiple of 8 for tensor-core efficiency
    safe = max(8, (int(best * 0.80) // 8) * 8)
    print(f"  [batch-tuner] Max={best}  Safe(80%)={safe}\n", flush=True)
    return safe


VALID_EXTS    = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# Folder names that are data-split dirs, not cell-type class labels — skip them
EXCLUDE_FOLDERS = {
    "C-NMC_test_final_phase_data",
    "C-NMC_test_prelim_phase_data",
    "testing_data",
    "training_data",
    "extracted",
}

# Suppress xFormers "not available" warnings — model works fine without it
warnings.filterwarnings("ignore", message="xFormers is not available")

# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

def class_from_path(path: Path) -> str:
    """
    Extract class label using the C-NMC filename convention:
        {patient_id}_{slide_id}_{image_id}_{CLASS}.ext
        e.g.  4_7_400_ALL.bmp  →  ALL
              UID_1_1_hem.bmp  →  hem

    Falls back to parent folder name when the last underscore segment
    is purely numeric or the filename has no underscores.
    """
    parts     = path.stem.split("_")
    candidate = parts[-1]
    if candidate and any(c.isalpha() for c in candidate):
        return candidate
    return path.parent.name


def load_txt_samples(txt_path: Path):
    samples = []
    if not txt_path.exists():
        return samples
    with open(txt_path, encoding="utf-8") as fh:
        for line in fh:
            rel = line.strip()
            if not rel:
                continue
            p = REPO_ROOT / rel
            samples.append((p, class_from_path(p)))
    return samples


def discover_samples(archive_dirs):
    samples = []
    for archive_dir in archive_dirs:
        for root, _, files in os.walk(archive_dir):
            if Path(root).name in EXCLUDE_FOLDERS:
                continue
            for fname in files:
                if Path(fname).suffix.lower() in VALID_EXTS:
                    fpath = Path(root) / fname
                    samples.append((fpath, class_from_path(fpath)))
    return samples


class BloodCellDataset(Dataset):
    def __init__(self, samples, class_to_idx, augment=False):
        self.samples      = samples
        self.class_to_idx = class_to_idx

        self.aug_tf = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomVerticalFlip(),
            transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
            transforms.RandomRotation(15),
        ]) if augment else None

        # Resize to 224x224 — DinoBloom-G was trained at this size.
        # ViT attention is quadratic in patch count so larger sizes OOM fast.
        self.to_tensor = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        try:
            img = Image.open(path).convert("RGB")
        except Exception:
            img = Image.new("RGB", (64, 64), (128, 128, 128))
        if self.aug_tf:
            img = self.aug_tf(img)
        return self.to_tensor(img), self.class_to_idx[label]


PATCH_SIZE = 14  # DinoBloom-G patch size — dimensions must be multiples of this

def _ceil14(n):
    """Round n up to the nearest multiple of PATCH_SIZE."""
    return ((n + PATCH_SIZE - 1) // PATCH_SIZE) * PATCH_SIZE

def pad_collate(batch):
    tensors, labels = zip(*batch)
    # Round max dims up to nearest multiple of 14
    max_h = _ceil14(max(t.shape[1] for t in tensors))
    max_w = _ceil14(max(t.shape[2] for t in tensors))
    padded = [F.pad(t, (0, max_w - t.shape[2], 0, max_h - t.shape[1])) for t in tensors]
    return torch.stack(padded), torch.tensor(labels, dtype=torch.long)


# ---------------------------------------------------------------------------
# DinoBloom-G with classification head
# ---------------------------------------------------------------------------

class DinoBloomClassifier(nn.Module):
    """
    DinoBloom-G backbone + MLP classification head.
    The last `unfreeze_blocks` transformer blocks are trainable.
    Everything else is frozen.
    """
    def __init__(self, backbone, num_classes: int, feat_dim: int = 1536, unfreeze_blocks: int = 4):
        super().__init__()
        self.backbone = backbone

        # Freeze everything first
        for p in self.backbone.parameters():
            p.requires_grad_(False)

        # Unfreeze the last N transformer blocks
        blocks = list(self.backbone.blocks)
        for block in blocks[-unfreeze_blocks:]:
            for p in block.parameters():
                p.requires_grad_(True)

        # Always unfreeze the final norm layer
        if hasattr(self.backbone, "norm"):
            for p in self.backbone.norm.parameters():
                p.requires_grad_(True)

        frozen  = sum(p.numel() for p in self.backbone.parameters() if not p.requires_grad)
        tunable = sum(p.numel() for p in self.backbone.parameters() if p.requires_grad)
        print(f"[backbone] frozen={frozen/1e6:.1f}M  trainable={tunable/1e6:.1f}M")

        # Classification head
        self.head = nn.Sequential(
            nn.LayerNorm(feat_dim),
            nn.Linear(feat_dim, 512),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(512, num_classes),
        )

    def forward(self, x):
        # ViT-G returns CLS token as the image representation
        features = self.backbone(x)          # (B, feat_dim)
        return self.head(features)


# ---------------------------------------------------------------------------
# Load DinoBloom-G backbone
# ---------------------------------------------------------------------------

def load_dinobloom_backbone(pth_path, device):
    sys.path.insert(0, str(REPO_ROOT))
    from dinov2.hub.backbones import dinov2_vitg14

    model = dinov2_vitg14(pretrained=False, img_size=224)
    raw   = torch.load(pth_path, map_location="cpu", weights_only=False)

    if isinstance(raw, dict):
        for key in ("teacher", "model", "state_dict"):
            if key in raw:
                raw = raw[key]
                break

    cleaned = {}
    for k, v in raw.items():
        for prefix in ("backbone.", "module.", "encoder."):
            if k.startswith(prefix):
                k = k[len(prefix):]
                break
        cleaned[k] = v

    missing, unexpected = model.load_state_dict(cleaned, strict=False)
    print(f"[DinoBloom-G] loaded | missing={len(missing)}  unexpected={len(unexpected)}")
    return model.to(device)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device : {device}")
    if device.type == "cuda":
        print(f"GPU    : {torch.cuda.get_device_name(0)}")
        print(f"VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # bf16 is natively faster on H200/A100 and needs no gradient scaler
    _bf16_ok  = device.type == "cuda" and torch.cuda.is_bf16_supported()
    amp_dtype = torch.bfloat16 if _bf16_ok else torch.float16
    print(f"AMP    : {'bfloat16 (native, no scaler needed)' if _bf16_ok else 'float16 + GradScaler'}")

    # ── Data ──────────────────────────────────────────────────────────────
    # archive5: use pre-defined 80/20 split from train.txt / val.txt
    txt_train_samples = load_txt_samples(REPO_ROOT / "New Data" / "train.txt")
    txt_val_samples   = load_txt_samples(REPO_ROOT / "New Data" / "val.txt")
    print(f"\n[txt]  archive5  {len(txt_train_samples)} train + {len(txt_val_samples)} val (pre-split 80/20)")

    # All archives except archive5 (which is handled by train.txt/val.txt above):
    # auto-discover every archiveN folder present so new archives from Google Drive
    # are picked up automatically without changing any code.
    extracted_root = REPO_ROOT / "New Data" / "extracted"
    archive_samples = []
    if extracted_root.exists():
        all_archives = sorted(
            [d for d in extracted_root.iterdir()
             if d.is_dir() and d.name.startswith("archive") and d.name != "archive5"],
            key=lambda p: p.name,
        )
        for d in all_archives:
            found = discover_samples([d])
            print(f"[dir]  {d.name}  →  {len(found)} images")
            archive_samples.extend(found)
    if not archive_samples:
        print("[dir]  No extra archives found beyond archive5 — using txt split only.")

    random.seed(42)
    random.shuffle(archive_samples)
    archive_split  = int(len(archive_samples) * 0.8)
    archive_train  = archive_samples[:archive_split]
    archive_val    = archive_samples[archive_split:]
    print(f"[dir]  extra archives  →  {len(archive_train)} train + {len(archive_val)} val (random 80/20)")

    train_samples = txt_train_samples + archive_train
    test_samples  = txt_val_samples   + archive_val

    if not train_samples:
        raise RuntimeError("No training samples found.")

    all_labels   = sorted({lbl for _, lbl in train_samples + test_samples})
    class_to_idx = {c: i for i, c in enumerate(all_labels)}
    num_classes  = len(class_to_idx)

    print(f"\nClasses ({num_classes}): {all_labels}")
    print(f"Train : {len(train_samples)} images")
    print(f"Test  : {len(test_samples)} images\n")

    with open(REPO_ROOT / "class_mapping.json", "w") as fh:
        json.dump(
            {"class_to_idx": class_to_idx,
             "idx_to_class": {v: k for k, v in class_to_idx.items()}},
            fh, indent=2,
        )

    train_ds = BloodCellDataset(train_samples, class_to_idx, augment=True)
    test_ds  = BloodCellDataset(test_samples,  class_to_idx, augment=False)

    # ── Model (loaded before DataLoaders so we can auto-tune batch size) ──
    print(f"Loading DinoBloom-G  (unfreezing last {args.unfreeze_blocks} blocks)...")
    backbone = load_dinobloom_backbone(str(REPO_ROOT / "DinoBloom-G.pth"), device)
    model    = DinoBloomClassifier(backbone, num_classes,
                                   unfreeze_blocks=args.unfreeze_blocks).to(device)

    total_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"[head]  trainable params in head: "
          f"{sum(p.numel() for p in model.head.parameters())/1e6:.1f}M")
    print(f"Total trainable: {total_trainable/1e6:.1f}M\n")

    # ── Auto-tune batch size ───────────────────────────────────────────────
    args.batch_size = find_max_batch_size(model, device, amp_dtype, num_classes)

    # ── torch.compile (PyTorch 2.0+ — 20-40% faster after first epoch) ───
    if hasattr(torch, "compile"):
        print("Compiling model with torch.compile (first epoch slower — one-time cost)...", flush=True)
        model = torch.compile(model)

    # ── DataLoaders (created after batch size is known) ───────────────────
    _mp_ctx = "fork" if args.workers > 0 else None
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True,
        num_workers=args.workers, pin_memory=True,
        persistent_workers=False,
        multiprocessing_context=_mp_ctx,
        collate_fn=pad_collate, drop_last=True,
    )
    test_loader = DataLoader(
        test_ds, batch_size=args.batch_size, shuffle=False,
        num_workers=args.workers, pin_memory=True,
        persistent_workers=False,
        multiprocessing_context=_mp_ctx,
        collate_fn=pad_collate,
    )
    print(f"DataLoaders ready — batch={args.batch_size}  workers={args.workers}\n", flush=True)

    # ── Optimiser — lower LR for backbone, higher for head ────────────────
    backbone_params = [p for p in model.backbone.parameters() if p.requires_grad]
    head_params     = list(model.head.parameters())

    optimizer = torch.optim.AdamW([
        {"params": backbone_params, "lr": args.lr * 0.1},   # fine-tune gently
        {"params": head_params,     "lr": args.lr},          # head learns faster
    ], weight_decay=1e-4)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6
    )
    scaler = None if amp_dtype == torch.bfloat16 else torch.amp.GradScaler("cuda")
    ce_fn  = nn.CrossEntropyLoss(label_smoothing=0.1)

    best_val_acc      = 0.0
    start_epoch       = 1
    out_path          = REPO_ROOT / "bloom_leukemia.pth"
    ckpt_path         = REPO_ROOT / "checkpoint_latest.pth"
    backup_dir        = REPO_ROOT / "backup"
    best_oracle_model = None   # tracks current best model object name in Oracle
    backup_dir.mkdir(exist_ok=True)

    # ── Metrics CSV ───────────────────────────────────────────────────────
    metrics_path = REPO_ROOT / "training_metrics.csv"
    if not metrics_path.exists():
        with open(metrics_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["epoch", "train_loss", "train_acc", "test_acc", "lr", "best_test_acc", "timestamp"])

    # ── Resume ────────────────────────────────────────────────────────────
    if args.resume and ckpt_path.exists():
        ckpt = torch.load(str(ckpt_path), map_location=device)
        model.load_state_dict(ckpt["model_state_dict"])
        optimizer.load_state_dict(ckpt["optimizer_state_dict"])
        scheduler.load_state_dict(ckpt["scheduler_state_dict"])
        if scaler is not None and ckpt.get("scaler_state_dict") is not None:
            scaler.load_state_dict(ckpt["scaler_state_dict"])
        start_epoch  = ckpt["epoch"] + 1
        best_val_acc = ckpt.get("best_val_acc", ckpt.get("best_train_acc", 0.0))
        print(f"[resume] Resuming from epoch {start_epoch}  (best val: {best_val_acc:.1f}%)\n")
    elif args.resume:
        print("[resume] No checkpoint found — starting from scratch.\n")

    # ── Epoch loop ────────────────────────────────────────────────────────
    reporter = EpochReporter(report_every=args.report_every)
    for epoch in range(start_epoch, args.epochs + 1):
        reporter.epoch_start()
        model.train()
        run_loss = 0.0
        correct  = total = 0

        for imgs, labels in train_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad(set_to_none=True)

            with torch.amp.autocast("cuda", dtype=amp_dtype):
                logits = model(imgs)
                loss   = ce_fn(logits, labels)

            if scaler is not None:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

            run_loss += loss.item()
            correct  += (logits.argmax(1) == labels).sum().item()
            total    += labels.size(0)

        scheduler.step()
        train_acc  = correct / total * 100
        train_loss = run_loss / len(train_loader)

        # ── Test evaluation ───────────────────────────────────────────────
        model.eval()
        test_correct = test_total = 0
        # Per-class tracking
        class_correct = [0] * num_classes
        class_total   = [0] * num_classes

        with torch.no_grad():
            for imgs, labels in test_loader:
                imgs, labels = imgs.to(device), labels.to(device)
                with torch.amp.autocast("cuda", dtype=amp_dtype):
                    logits = model(imgs)
                preds = logits.argmax(1)
                test_correct += (preds == labels).sum().item()
                test_total   += labels.size(0)
                for p, l in zip(preds, labels):
                    class_correct[l.item()] += (p == l).item()
                    class_total[l.item()]   += 1

        test_acc = test_correct / test_total * 100

        # ── Compact per-epoch line ─────────────────────────────────────────
        idx_to_class  = {v: k for k, v in class_to_idx.items()}
        cur_lr        = scheduler.get_last_lr()[0]
        epoch_time    = _time.time() - reporter._epoch_start if reporter._epoch_start else 0
        ta_col        = _acc_color(train_acc)
        va_col        = _acc_color(test_acc)
        elapsed_total = epoch_time * epoch
        eta_secs      = epoch_time * (args.epochs - epoch)
        eta_str       = f"{int(eta_secs//3600):02d}h{int((eta_secs%3600)//60):02d}m"
        print(
            f"Ep {epoch:>3}/{args.epochs}"
            f"  loss {_c('yellow', f'{train_loss:.4f}')}"
            f"  tr {_c(ta_col, f'{train_acc:.2f}%')}"
            f"  val {_c(va_col, f'{test_acc:.2f}%')}"
            f"  best {_c('green', f'{best_val_acc:.2f}%')}"
            f"  lr {_c('grey', f'{cur_lr:.1e}')}"
            f"  {epoch_time:.0f}s  ETA {_c('grey', eta_str)}",
            flush=True
        )

        # ── Verbose epoch report every N epochs ───────────────────────────
        per_class_accs = {
            idx_to_class[i]: {
                "acc":     class_correct[i] / class_total[i] * 100 if class_total[i] > 0 else 0.0,
                "correct": class_correct[i],
                "total":   class_total[i],
            }
            for i in range(num_classes)
        }
        reporter.report(
            epoch=epoch,
            total_epochs=args.epochs,
            model=model,
            optimizer=optimizer,
            train_loss=train_loss,
            val_loss=None,
            train_acc=train_acc / 100,
            val_acc=test_acc / 100,
            extra={
                "lr":               cur_lr,
                "per_class":        per_class_accs,
                "train_samples":    len(train_samples),
                "val_samples":      len(test_samples),
                "num_classes":      num_classes,
                "batch_size":       args.batch_size,
                "unfreeze_blocks":  args.unfreeze_blocks,
                "epoch_secs":       epoch_time,
            },
        )

        # ── Log metrics to CSV ────────────────────────────────────────────
        with open(metrics_path, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([epoch, round(train_loss, 4), round(train_acc, 2),
                             round(test_acc, 2), f"{scheduler.get_last_lr()[0]:.2e}",
                             round(best_val_acc, 2), time.strftime("%Y-%m-%d %H:%M:%S")])

        # Save resume checkpoint every epoch
        ckpt_data = {
            "epoch"               : epoch,
            "best_train_acc"      : best_val_acc,
            "model_state_dict"    : model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "scaler_state_dict"   : scaler.state_dict() if scaler is not None else None,
            "num_classes"         : num_classes,
            "class_to_idx"        : class_to_idx,
        }
        torch.save(ckpt_data, str(ckpt_path))

        if not args.no_oracle:
            # Upload per-epoch backup to Oracle in background — no disk buildup
            backup_path = backup_dir / f"checkpoint_epoch_{epoch:03d}.pth"
            torch.save(ckpt_data, str(backup_path))
            _bp = str(backup_path)
            _bobj = f"{OCI_RUN_PREFIX}/backups/checkpoint_epoch_{epoch:03d}.pth"
            def _upload_backup(p=_bp, obj=_bobj, lp=backup_path):
                try:
                    oracle_upload(p, obj)
                    lp.unlink(missing_ok=True)
                    print(f"  [backup] {lp.name} → Oracle done, local removed", flush=True)
                except Exception as e:
                    print(f"  [backup] WARNING: {lp.name} upload failed — {e}", flush=True)
            import threading as _threading
            _threading.Thread(target=_upload_backup, daemon=True).start()

            # Upload last checkpoint to Oracle in background
            oracle_upload_bg(str(ckpt_path), f"{OCI_RUN_PREFIX}/last_epoch{epoch:03d}.pth")
            oracle_upload_bg(str(ckpt_path), f"{OCI_RUN_PREFIX}/last.pth")

        # Save best model whenever test accuracy improves
        if test_acc > best_val_acc:
            best_val_acc = test_acc
            torch.save(
                {
                    "epoch"           : epoch,
                    "train_acc"       : round(train_acc, 4),
                    "test_acc"        : round(test_acc, 4),
                    "num_classes"     : num_classes,
                    "class_to_idx"    : class_to_idx,
                    "arch"            : "bloom_leukemia",
                    "unfreeze_blocks" : args.unfreeze_blocks,
                    "model_state_dict": model.state_dict(),
                },
                str(out_path),
            )
            print(f"  *** New best model — epoch {epoch} — test_acc={test_acc:.2f}% ***")
            if not args.no_oracle:
                new_oracle_model = f"{OCI_RUN_PREFIX}/best_epoch{epoch:03d}_{test_acc:.2f}pct.pth"
                best_oracle_model = new_oracle_model
                oracle_upload_bg(str(out_path), new_oracle_model)
                oracle_upload_bg(str(out_path), f"{OCI_RUN_PREFIX}/best.pth")

    # ── Final uploads to Oracle ───────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"  Training complete.  Best val acc: {best_val_acc:.2f}%")
    print(f"  Uploading final models to Oracle...")
    print(f"  Prefix: {OCI_RUN_PREFIX}")
    print(f"{'='*60}")

    if not args.no_oracle:
        if ckpt_path.exists():
            try:
                oracle_upload(str(ckpt_path), f"{OCI_RUN_PREFIX}/last_epoch{args.epochs:03d}.pth")
                oracle_upload(str(ckpt_path), f"{OCI_RUN_PREFIX}/last.pth")
                print(f"  [oracle] last_epoch{args.epochs:03d}.pth uploaded.")
            except Exception as e:
                print(f"  [oracle] WARNING: final last upload failed — {e}")

        if metrics_path.exists():
            try:
                oracle_upload(str(metrics_path), f"{OCI_RUN_PREFIX}/training_metrics.csv")
                print(f"  [oracle] training_metrics.csv uploaded.")
            except Exception as e:
                print(f"  [oracle] WARNING: metrics upload failed — {e}")

    print(f"\n  All done.")
    print(f"  best.pth  = {out_path}")
    print(f"  last.pth  = {ckpt_path}")


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs",          type=int,   default=30)
    parser.add_argument("--batch-size",      type=int,   default=4,
                        help="Keep at 4-8 — DinoBloom-G is large")
    parser.add_argument("--lr",              type=float, default=1e-4,
                        help="Head LR. Backbone gets lr*0.1 to fine-tune gently")
    parser.add_argument("--unfreeze-blocks", type=int,   default=4,
                        help="How many of DinoBloom-G's last transformer blocks to unfreeze")
    parser.add_argument("--workers",         type=int,   default=4)
    parser.add_argument("--resume",          action="store_true")
    parser.add_argument("--report-every",   type=int,   default=5)
    parser.add_argument("--no-oracle",      action="store_true",
                        help="Skip all Oracle uploads (for local training)")
    args = parser.parse_args()
    train(args)
